### ISSUE TITLE
Searching dates error 

### ISSUE THREAD

**Issue by Chrisvann1** [Chrisvann1/Software-Engineering-Note-Taking-Application#64]
how to reproduce your error - I used the modified date search function. 
start date I tried two different things: 
     - I left the start date blank 
     - I put 0000-00-00 for the start date

End date: 
     - 2024-12-12
   
what the expected behavior is 
     - Return the fields specified by the frontend (modified date, title, created date)
   
what the actual behavior is 
     - Error codes relating to the dates
     
and what error the code is returning?
     - ValueError: time data '' does not match format '%Y-%m-%d'
     - ValueError: time data '0000-00-00' does not match format '%Y-%m-%d'

**Comment by tferrelCOW** [comment]
**Adding some to this error. Currently, it is printing this, meaning the apiCalls function is returning this from API response.**

File Name: 
   stylesheet

Created Date: 
   ?__debugger__=yes&amp;cmd=resource&amp;f=style.css

Modified Date: 
   shortcut icon



File Name: 
   ?__debugger__=yes&amp;cmd=resource&amp;f=console.png

Created Date: 
   ?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js

Modified Date: 
   FgFuDh8xJZ9behK2JAHE



File Name: 
   background-color: #fff

Created Date: 
   debugger

Modified Date: 
   detail



File Name: 
   errormsg

Created Date: 
   traceback

Modified Date: 
   traceback



File Name: 
   frame

Created Date: 
   frame-2250735394176

Modified Date: 
   filename



File Name: 
   C:\Users\Trent\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py

**Comment by augustus-thomas** [comment]
Thanks for this helpful info! It would have helped to know if you were calling the endpoints directly and what the tracebacks were. It turned out the problem was because `app.py` did not set the defaults for search date ranges directly, it relied on `apiCalls.py` to do that. Probably wasn't the best design decision. I made those changes in the PR above!
