### ISSUE TITLE
Fully Refactoring Backend

### ISSUE THREAD

**Issue by augustus-thomas** [Chrisvann1/Software-Engineering-Note-Taking-Application#8]
@Chrisvann1 @jteferi @lindaassefa 

It was pointed out to me by Drew today that the endpoints in our API should correspond to objects, and the HTTP methods should correspond to the functions we call on those objects. Right now our endpoints are named after verbs like "create" and "delete." They should be named nouns like "tags" and "notes" Each endpoint should support many methods like GET, PUT etc. The functionality of adding and deleting an object from our tables should correspond to these methods. We could redesign the schema for the objects.

Please let me know if you approve of this design change. If I get approval I'll make an API spec doc for the endpoints and their corresponding methods, along with their corresponding payloads.

**Comment by Chrisvann1** [comment]
Hello, that sounds like a good idea to me. I am not sure what it would look like however to have each endpoint support many methods so I would probably need some sort of example of that.

**Comment by lindaassefa** [comment]
Actually, aligning the endpoints with nouns representing objects and using HTTP methods to correspond to actions on those objects can lead to a more intuitive and standardized API structure. I approve of this design change as it keeps consistency and clarity in our API architecture

**Comment by augustus-thomas** [comment]
This problem is resolved with the addition of "list" and "search" and the refactoring as suggested by @F1shbol
